topics:
  - input: "/morai/sensors/servo_position_command"
    output: "/sensors/servo_position_command"
    type: "std_msgs/Float64"
    processor: "servo_position_command"
  - input: "/morai/GetTrafficLightStatus"
    output: "/GetTrafficLightStatus"
    type: "morai_msgs/GetTrafficLightStatus"
    processor: "GetTrafficLightStatus"
  - input: "/morai/imu"
    output: "/imu"
    type: "sensor_msgs/Imu"
    processor: "imu" 
  - input: "/morai/sensors/core"
    output: "/sensors/core"
    type: "vesc_msgs/VescStateStamped"
    processor: "sensors_core" 
